version: 2.1

# ## Workflows
#
# ### Contiunous Ruby Update
#
# 1. Check the newest Ruby (scheduled)
# 1. If a new Ruby found, create a new Pull Request
#     - Created branch is named `ruby-{major}.{minor}.{patch}`
#     - After git push, CircleCI trigger default workflow
#
# ### Default workflow
#
# NOTE: Start workflow only if branch name matches `master` or `ruby-*`.
#
# 1. Build Ruby RPM
# 1. Test Ruby RPM
# 1. Deploy Ruby RPM if the branch is `master`
#
# ## ENV (CircleCI)
#
# | Name                    | Description                              | Example                                              |
# | ----------------------- | ---------------------------------------- | ---------------------------------------------------- |
# | `GITHUB_TOKEN`          | GitHub API Token to use to create PR.    | "<Secret>"                                           |
# | `GIT_CONFIG_USER_EMAIL` | Email address to use git commit message. | "technical_staff@feedforce.jp"                       |
# | `GIT_CONFIG_USER_NAME`  | User name to use git commit message.     | "feedforce tech team"                                |
# | `CHANGELOG_AUTHOR`      | Author to write SPEC changelog.          | "feedforce tech team <technical_staff@feedforce.jp>" |
#
# ## Usage
#
# ### To add a new Ruby version
#
# 1. Add a new SPEC file as `ruby-{major}.{minor}.spec` to repository
# 1. Add jobs of a new Ruby version to workflows in `.circleci/config.yml`
#

executors:
  amd64:
    machine:
      image: ubuntu-2004:202104-01
    environment:
      DOCKER_BUILD_KIT: 1

  arm64:
    machine:
      image: ubuntu-2004:202104-01
    environment:
      DOCKER_BUILD_KIT: 1
    resource_class: arm.medium

jobs:
  build_and_test:
    parameters:
      version:
        description: Ruby version (e.g. 2.5)
        type: enum
        enum:
          - "2.6"
          - "2.7"
          - "3.0"
      arch:
        type: enum
        enum:
          - "amd64"
          - "arm64"
    executor: << parameters.arch >>
    working_directory: ~/ruby-rpm
    steps:
      - checkout
      - run:
          name: "Build Docker image for Ruby RPM << parameters.version >>"
          command: |
            docker build \
              -t feedforce/ruby-rpm:<< parameters.version >>-builder \
              -f Dockerfile-7 \
              --target builder \
              --cache-from=feedforce/ruby-rpm:centos7 \
              --build-arg RUBY_X_Y_VERSION=<< parameters.version >> \
              --progress plain \
              .
      - run:
          name: "Extract RPM file from Docker container"
          command: |
            CONTAINER_ID=$(docker create feedforce/ruby-rpm:<< parameters.version >>-builder)
            docker cp ${CONTAINER_ID}:/tmp/ruby-<< parameters.version >>-rpm/ /tmp/
      - store_artifacts:
          path: "/tmp/ruby-<< parameters.version >>-rpm"
          destination: "ruby-<< parameters.version >>-rpm"
      - run:
          name: "Build Docker image to install Ruby RPM << parameters.version >>"
          command: |
            docker build \
              -t feedforce/ruby-rpm:<< parameters.version >>-tester \
              -f Dockerfile-7 \
              --target tester \
              --cache-from=feedforce/ruby-rpm:<< parameters.version >>-builder \
              --build-arg RUBY_X_Y_VERSION=<< parameters.version >> \
              --progress plain \
              .
      - run:
          name: "Run Ruby << parameters.version >>"
          command: |
            docker run -it feedforce/ruby-rpm:<< parameters.version >>-tester \
              ruby -v -e 'puts File.read("/etc/centos-release")'
      - run:
          name: "Uninstall Ruby RPM << parameters.version >>"
          command: |
            docker run -it feedforce/ruby-rpm:<< parameters.version >>-tester \
              yum remove -y ruby
      - persist_to_workspace:
          root: "/tmp/ruby-<< parameters.version >>-rpm"
          paths:
            - ./*

  deploy:
    parameters:
      version:
        description: Ruby version (e.g. 2.5)
        type: enum
        enum:
          - "2.6"
          - "2.7"
          - "3.0"
    docker:
      # Although the Golang is not necessary, the CircleCI official image is used for fast downloading.
      - image: circleci/golang
        environment:
          CIRCLE_ARTIFACTS: "/tmp/ruby-<< parameters.version >>-rpm"
    working_directory: ~/ruby-rpm
    steps:
      - checkout
      - attach_workspace:
          at: "/tmp/ruby-<< parameters.version >>-rpm"
      - deploy:
          name: "Deploy Ruby RPM << parameters.version >>"
          command: "./.circleci/github-release.sh << parameters.version >>"

  update:
    docker:
      # Although the Golang is not necessary, the CircleCI official image is used for fast downloading.
      - image: circleci/golang
    working_directory: ~/ruby-rpm
    steps:
      - checkout
      - run:
          name: Update SPEC files
          command: ./.circleci/update-spec.sh

workflows:
  version: 2
  default:
    jobs:
      - build_and_test:
          name: ruby-<< matrix.version >>-centos7-<< matrix.arch >>-build-and-test
          matrix:
            parameters:
              version: ["2.6", "2.7", "3.0"]
              arch: ["amd64", "arm64"]
      - deploy:
          name: ruby-<< matrix.version >>-deploy
          matrix:
            parameters:
              version: ["2.6", "2.7", "3.0"]
          requires:
            - ruby-<< matrix.version >>-centos7-amd64-build-and-test
            - ruby-<< matrix.version >>-centos7-arm64-build-and-test
          filters:
            branches:
              only:
                - master

  continuous_update:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update
